name: 'Docs Validator CI'

on: [push]

jobs:
  test_action:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout code'
        uses: actions/checkout@v4

      - name: 'Install dependencies'
        run: npm install

      - name: 'Run tests'
        run: npm test

      - name: 'Package the action'
        run: npm run package

      - name: 'Run the action'
        uses: ./
        with:
          manifest-url: ${{ secrets.MANIFEST_URL }}
          token: ${{ secrets.DOCS_REPO_PAT }}
          repo-url: ${{ secrets.REPO_URL }}